### PR TITLE
Removed namespace for qt declaraction

### PR DESCRIPTION
**Pull request by erlend-g**
Fixed bug in qml-demo-shell.. But removing qtmir from Qt declaraction.

file:///home/erlend/qtmir/demos/qml-demo-shell/qml-demo-shell.qml:28: Error: Unknown method parameter type: FormFactor

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Not sure about this. I don't see the error you refer to (maybe you can give a reproducer), but I do see
```
QMetaProperty::read: Unable to handle unregistered datatype 'FormFactor' for property 'qtmir::QQuickScreenWindow::formFactor'
```
both with and without this PR.

**Comment by erlend-g** [comment]
I'm not 100% percent just either... But Running the qml-demo-shell without PR and pressing (ScaleUp)

Gives (console output):
file:///home/erlend/qtmir/demos/qml-demo-shell/qml-demo-shell.qml:28: Error: Unknown method parameter type: FormFactor

With the PR:
qtmir.screens: ScreensModel::update
qtmir.screens: Can reuse Screen with id 1
qtmir.screens: =======================================
qtmir.screens: Screen(0x7f6ff0348b90) - id: 1 geometry: QRect(0,0 1280x930) window: QPlatformSurface(0xacf490, class=QSurface::Window, type=QSurface::OpenGLSurface, window=qtmir::QQuickScreenWindow(0xace730)) type: "Unknown" scale: 1.2
qtmir.screens: =======================================
[2021-05-02 20:46:54.877477] <information> mirserver: New base display configuration:
[2021-05-02 20:46:54.877523] <information> mirserver: * Output 1: unknown connected, used
[2021-05-02 20:46:54.877566] <information> mirserver: . |_ Physical size 16,5" 338x246mm
[2021-05-02 20:46:54.877590] <information> mirserver: . |_ Power is on
[2021-05-02 20:46:54.877613] <information> mirserver: . |_ Current mode 1280x930 60,00Hz
[2021-05-02 20:46:54.877637] <information> mirserver: . |_ Preferred mode 1280x930 60,00Hz
[2021-05-02 20:46:54.877659] <information> mirserver: . |_ Orientation normal
[2021-05-02 20:46:54.877734] <information> mirserver: . |_ Logical size 1067x775
[2021-05-02 20:46:54.877759] <information> mirserver: . |_ Logical position +0+0
[2021-05-02 20:46:54.877782] <information> mirserver: . |_ Scaling factor: 1,20
[2021-05-02 20:46:54.877898] <information> miroil: Failed to parse EDID - Incorrect EDID structure size
so with the PR it seems to run longer..  but there are still errors (haven't investigated the parse error jet).

I googled a bit and found this:
https://stackoverflow.com/questions/22044737/when-where-and-why-use-namespace-when-registering-custom-types-for-qt

Which recommends adding both with and without namespace... So I have updated it to do that....

So what do you think?

**Comment by AlanGriffiths** [comment]
@gerboland  suggestions?

**Comment by gerboland** [comment]
First off, please check `Q_DECLARE_METATYPE` been used to [declare](https://doc.qt.io/qt-5/qmetatype.html#qRegisterMetaType-1) `FormFactor`?

[This](https://stackoverflow.com/questions/22044737/when-where-and-why-use-namespace-when-registering-custom-types-for-qt) is the most authoritative reference I can find, and it is several years old unfortunately. I used to write
```
qRegisterMetaType<qtmir::FormFactor>("qtmir::FormFactor");
```
because it appeared that Qt would ignore the namespace specifier in the string, and so it was equivalent to 
```
qRegisterMetaType<qtmir::FormFactor>("FormFactor");
```
So I'd be surprised if this patch actually changes anything. However Qt has changed a bunch since 2014!

You do need to make sure `qRegisterMetaType` is actually called before the type is used. It is a run-time registry, so passing a FormFactor pointer using signal/slot will print that `unregistered datatype` message if called before `qRegisterMetaType`. A quick qDebug() can clear that up at least.

**Review by AlanGriffiths — APPROVED** [review]
Thanks @gerboland, I've not spent the time to figure out exactly what is going on but `registerTypes()` IS being called before the error occurs, and the patch does make a difference.

**Pull request merged**
